config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  resources :projects do
    resources :tasks
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project, dependent: :destroy
  belongs_to :user, dependent: :destroy
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project, only: [ :create, :destroy ]
  before_action :set_task, only: %i[ destroy ]

  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.create(task_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_url(@project), notice: "Task was successfully created." }
      else
        # Log error
        puts @task.errors.full_messages.join(', ')

        format.html { redirect_to project_url(@project), notice: "There was an error creating the task." }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    redirect_to @project
  end

    private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_project
        @project = Project.find(params[:project_id])
    end

    def set_task
        @task = @project.tasks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:content)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@project, @project.tasks.build]) do |f| %>
  <div class="mb-3">
  <%= f.text_field :content, placeholder: "New task", class:"form-control" %>
  </div>
  <%= f.submit "Add task", class:"btn btn-primary" %>
<% end %>

app/views/tasks/_task.html.erb
<li class="d-flex gap-2 mb-3">
    <p>
        <%= task.content %>
    </p>
    
    <%= button_to "Delete", project_task_path(@project, task), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
</li>

app/views/tasks/_tasks.html.erb
<ul>
    <% unless @tasks.nil? && @tasks.empty? %>
        <% @tasks.each do |task| %>
            <%= render task %>
        <% end %>
    <% else %>
        <li>You have no tasks for this project.</li>
    <% end %>
</ul>